name: PR Screenshot

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  screenshot:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.event.pull_request.head.ref }}
      REPO: ${{ github.event.pull_request.head.repo.full_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install playwright Pillow
          playwright install --with-deps chromium
      - name: Capture screenshots
        run: |
          python .github/scripts/screenshot.py --out output > screenshot.log 2>&1
      - name: Copy screenshots into repo
        run: |
          mkdir -p screenshots
          for f in output/screenshot-*.jpg; do
            lang=$(basename "$f" | sed 's/screenshot-//')
            cp "$f" "screenshots/$lang"
          done
      - name: Upload screenshots artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-screenshots
          path: screenshots
      - name: Commit screenshots
        env:
          BRANCH: ${{ env.BRANCH }}
        run: |
          set -eo pipefail
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add screenshots/*.jpg
          if ! git diff --cached --quiet; then
            git commit -m "Add screenshots [skip ci]" > push.log 2>&1
            git push origin HEAD:$BRANCH >> push.log 2>&1
          else
            echo "No changes" > push.log
          fi
      - name: Upload push log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: push-log
          path: push.log
      - name: Comment screenshot URLs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BRANCH: ${{ env.BRANCH }}
          REPO: ${{ env.REPO }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          body="Download screenshots from [workflow run artifacts]($RUN_URL)"
          for f in screenshots/*.jpg; do
            lang=$(basename "$f" .jpg)
            url="https://github.com/${REPO}/raw/${BRANCH}/screenshots/$lang.jpg"
            body+="\n![${lang}](${url})"
          done
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               -d "{\"body\":\"$body\"}" \
               "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments"
