name: Update Translations

on:
  push:
    paths:
      - 'i18n/zh-tw.json'
      - 'music/base.json'
      - '.github/scripts/translate.py'
      - '.github/workflows/update_translate.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Check music base changes
        id: base
        run: |
          if git diff --quiet ${{ github.event.before }} HEAD -- music/base.json; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Translate all languages
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          for lang in en es ja ko pt zh-cn zh-hk; do
            python .github/scripts/translate.py i18n/zh-tw.json i18n/$lang.json
            if [ "${{ steps.base.outputs.changed }}" = "true" ]; then
              python .github/scripts/translate.py music/base.json music/$lang.json
            fi
          done
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add i18n/*.json music/*.json
            git commit -m "Update translations"
            git push
          fi
