name: Update Embeddings
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Load languages
        id: langs
        run: |
          list=$(ls app/*.html | xargs -n1 basename | sed 's/\.html$//' | grep -v '^index$' | tr '\n' ' ')
          echo "list=$list" >> "$GITHUB_OUTPUT"
      - name: Update embeddings
        run: |
          for lang in ${{ steps.langs.outputs.list }}; do
            file="music/$lang.json"
            if [ -f "$file" ]; then
              python .github/scripts/embedding.py "$file"
            fi
          done
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            files=$(git status --porcelain music/*.json | awk '{print $2}' | tr '\n' ' ')
            git add music/*.json
            git commit -m "Update embeddings [skip ci]" -m "$files"
            git push
          fi
